// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Cheap pre-open check: does the project parse, and can its engine be resolved? */
	validateProject: (uprojectPath: string) => typedError<ProjectValidation, AppError>(__TAURI_INVOKE("validate_project", { uprojectPath })),
	/**
	 *  Full detection + record the recent. Requires both the project and a valid
	 *  engine (saved or auto-resolved) - otherwise `EngineNotFound`.
	 */
	openProject: (uprojectPath: string) => typedError<DetectedProject, AppError>(__TAURI_INVOKE("open_project", { uprojectPath })),
	/**
	 *  Full plugin detection + record the recent. A plugin packages standalone, so this
	 *  needs no engine (the compile engine is chosen per-package in the Actions tab).
	 */
	openPlugin: (pluginPath: string) => typedError<DetectedPlugin, AppError>(__TAURI_INVOKE("open_plugin", { pluginPath })),
	/**
	 *  The currently-open plugin (read-only snapshot of managed state), or `None`. Powers
	 *  the Actions tab's package action + engine picker.
	 */
	currentPlugin: () => typedError<{
	/**  File stem of the `.uplugin` (the canonical plugin name UAT uses). */
	name: string,
	friendlyName: string,
	versionName: string,
	upluginPath: string,
	/**
	 *  Directory containing the `.uplugin` (where `-package` output and the
	 *  `.uep/local.json` remembered-engines file are anchored).
	 */
	pluginRoot: string,
	/**  `.uplugin`'s `EngineVersion` (e.g. `"5.5"`), or `None` if unset. */
	engineVersion: string | null,
} | null, AppError>(__TAURI_INVOKE("current_plugin")),
	/**
	 *  Validate a user-picked engine folder; on success, save it as this **project's**
	 *  engine override (`.uep/local.json`) - per-project, so it never bleeds into other
	 *  projects that happen to share the same `EngineAssociation`.
	 */
	locateEngine: (uprojectPath: string, engineDir: string) => typedError<EngineInfo, AppError>(__TAURI_INVOKE("locate_engine", { uprojectPath, engineDir })),
	/**
	 *  Recents with freshly-validated project + engine status (nothing cached).
	 *  Invalid entries are kept - the UI flags the offending part with a fix
	 *  affordance and offers Remove via the row menu; only an explicit Remove drops
	 *  a recent.
	 */
	listRecents: () => typedError<RecentEntry[], AppError>(__TAURI_INVOKE("list_recents")),
	removeRecent: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_recent", { path })),
	/**  Pin/unpin a recent (persisted). Pinned entries sort to the top of the list. */
	setRecentStarred: (path: string, starred: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_recent_starred", { path, starred })),
	/**
	 *  The currently-open detected project (read-only snapshot of managed state), or
	 *  `None` if none is open. Powers the Build Settings editor's target/map pickers
	 *  and output preview without re-running detection.
	 */
	currentProject: () => typedError<{
	name: string,
	uprojectPath: string,
	projectRoot: string,
	engineAssociation: string,
	engine: EngineInfo,
	projectType: ProjectType,
	targets: TargetInfo[],
	maps: MapInventory,
	plugins: string[],
} | null, AppError>(__TAURI_INVOKE("current_project")),
	listProfiles: () => typedError<BuildConfig[], AppError>(__TAURI_INVOKE("list_profiles")),
	/**
	 *  Create a profile by cloning a template or another profile (never blank), then
	 *  persist and return it (copy-on-create; no live link to the source).
	 */
	createProfile: (req: CreateRequest) => typedError<BuildConfig, AppError>(__TAURI_INVOKE("create_profile", { req })),
	/**  Duplicate a profile into a self-contained `<name> (copy)`. */
	duplicateProfile: (id: string) => typedError<BuildConfig, AppError>(__TAURI_INVOKE("duplicate_profile", { id })),
	/**  Validate (authoritative) then persist a profile. */
	saveProfile: (profile: BuildConfig) => typedError<null, AppError>(__TAURI_INVOKE("save_profile", { profile })),
	deleteProfile: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_profile", { id })),
	/**  Global templates - the fixed built-ins (self-healed) plus user templates. */
	listTemplates: () => typedError<BuildConfig[], AppError>(__TAURI_INVOKE("list_templates")),
	/**
	 *  Create a user template by cloning an existing one (a fixed built-in, or any
	 *  user template) - never blank. Persist + return it.
	 */
	createTemplate: (req: CreateTemplateRequest) => typedError<BuildConfig, AppError>(__TAURI_INVOKE("create_template", { req })),
	/**
	 *  Persist a user template. Built-ins are read-only; a template may omit the
	 *  output base dir (project-agnostic), so only id + name are required.
	 */
	saveTemplate: (template: BuildConfig) => typedError<null, AppError>(__TAURI_INVOKE("save_template", { template })),
	/**  Delete a user template. The fixed built-in(s) cannot be deleted. */
	deleteTemplate: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_template", { id })),
	/**
	 *  Resolve a profile (possibly with unsaved edits) into the read-only per-phase
	 *  command preview, against the currently-open project. `{date}`/`{time}` resolve
	 *  to now (local).
	 */
	previewProfile: (profile: BuildConfig) => typedError<PhaseCommand[], AppError>(__TAURI_INVOKE("preview_profile", { profile })),
	/**
	 *  The static phase registry (for the editor's phase-structured layout). Includes
	 *  each phase's `gated_by`, from which the editor derives locked/enabled itself.
	 */
	phaseRegistry: () => __TAURI_INVOKE<PhaseInfo[]>("phase_registry"),
	/**
	 *  Resolve a profile against the open project and launch its pipeline. Returns the
	 *  new run id; progress arrives via `uep://run-*` events. Refuses a second
	 *  concurrent run.
	 */
	startBuild: (profile: BuildConfig) => typedError<string, AppError>(__TAURI_INVOKE("start_build", { profile })),
	/**
	 *  Signal the active run to cancel (kills running children, settles the graph).
	 *  No-op when nothing is running.
	 */
	cancelBuild: () => typedError<null, AppError>(__TAURI_INVOKE("cancel_build")),
	/**
	 *  Snapshot of the in-flight (or most recent) run - lets a freshly-opened Build
	 *  Logs window render the graph + backfill the console before following events.
	 */
	activeRun: () => typedError<{
	runId: string,
	project: string,
	platform: string,
	config: string,
	target: string,
	outputDir: string,
	startedMs: number | null,
	status: RunStatus,
	phases: PhaseNode[],
	lines: LogLine[],
	/**
	 *  Single resolved command line - set for a plugin-package run or an editor-commandlet
	 *  tool run (the Run Log window shows it). Empty for a build run, whose per-phase
	 *  commands live on the `phases` nodes instead.
	 */
	command: string,
	/**
	 *  Heading for the single-command Run Log window: "Package Plugin" for a plugin
	 *  package, the tool name ("Resave Assets" / "Validate Assets") for a commandlet tool.
	 *  Empty for a build run (the Build Logs window has its own heading).
	 */
	title: string,
} | null, AppError>(__TAURI_INVOKE("active_run")),
	/**
	 *  Resolve a profile's archive dir and report whether it already exists - drives
	 *  the Run-time "folder already exists, replace?" confirm (R1).
	 */
	checkOutput: (profile: BuildConfig) => typedError<OutputCheck, AppError>(__TAURI_INVOKE("check_output", { profile })),
	/**
	 *  All build records for the open project, newest first. (Powers the Dashboard,
	 *  which aggregates over the whole history; the Build tab pages via
	 *  [`list_history_page`].)
	 */
	listHistory: () => typedError<BuildRecord[], AppError>(__TAURI_INVOKE("list_history")),
	/**
	 *  One filtered, newest-first **page** of history via the SQLite index (R5). Falls
	 *  back to a direct file scan if the index can't be opened/queried, so history never
	 *  disappears on a DB hiccup (the JSON records are the source of truth).
	 */
	listHistoryPage: (offset: number, limit: number, filter: HistoryFilter) => typedError<HistoryPage, AppError>(__TAURI_INVOKE("list_history_page", { offset, limit, filter })),
	/**  A past build's record + its saved log (for Build Logs replay). */
	historyDetail: (buildId: string) => typedError<{
	record: BuildRecord,
	/**
	 *  The saved log, re-classified for severity tinting on replay; each line's
	 *  phase index is restored from the `build.idx` sidecar (0 for older records).
	 */
	lines: LogLine[],
} | null, AppError>(__TAURI_INVOKE("history_detail", { buildId })),
	/**  Delete one or more build records (folders). Idempotent. */
	deleteHistory: (ids: string[]) => typedError<null, AppError>(__TAURI_INVOKE("delete_history", { ids })),
	/**
	 *  Integrity check before "Open location" (R5): confirms the output folder still
	 *  holds *this* build. The primary signal is metadata, not the filesystem - a later
	 *  build that archived to the **same folder** overwrote this one's output, so opening
	 *  the older record would actually show the newer build. (The directory's own mtime
	 *  is unreliable here: NTFS doesn't bump a folder's mtime when only nested files are
	 *  rewritten, which is exactly the same-folder rebuild case.) mtime drift is kept as
	 *  a secondary signal for out-of-band edits. The UI opens the folder, or warns.
	 */
	checkBuildLocation: (buildId: string) => typedError<LocationCheck, AppError>(__TAURI_INVOKE("check_build_location", { buildId })),
	/**
	 *  Scan the open project's reclaimable footprint, bucketed by category (R3). Heavy walk
	 *  → off the UI thread via `spawn_blocking`.
	 */
	scanFootprint: () => typedError<FootprintReport, AppError>(__TAURI_INVOKE("scan_footprint")),
	/**
	 *  Delete the chosen Clean-tab nodes and report bytes reclaimed (R3). `node_ids` are leaf
	 *  ids from the scan (e.g. `intermediateGame:<target>`, `intermediateOther`, `binariesPlugin`).
	 *  The UI shows the confirm prompt that lists every folder *before* calling this; the
	 *  backend re-resolves the tree and re-validates each target against the guardrail. Heavy
	 *  delete → off the UI thread.
	 */
	cleanFootprint: (nodeIds: string[]) => typedError<CleanOutcome, AppError>(__TAURI_INVOKE("clean_footprint", { nodeIds })),
	/**  Current app settings (defaults if never saved). */
	loadSettings: () => typedError<AppSettings, AppError>(__TAURI_INVOKE("load_settings")),
	/**
	 *  Persist app settings and broadcast `uep://settings-changed` so every open window
	 *  re-applies the theme live (each window is its own webview).
	 */
	saveSettings: (settings: AppSettings) => typedError<null, AppError>(__TAURI_INVOKE("save_settings", { settings })),
	/**  The app version (from `Cargo.toml`) - for the Settings "About" line. */
	appVersion: () => __TAURI_INVOKE<string>("app_version"),
	/**
	 *  Hide the main window and reveal the tray icon - the "minimize to tray" choice
	 *  when the user closes the main window while a build is running. The build keeps
	 *  running (the window is hidden, not destroyed); the tray restores it. (Restore +
	 *  re-hide of the tray happens in the tray's own click/Show handlers in `lib.rs`.)
	 */
	minimizeToTray: () => typedError<null, AppError>(__TAURI_INVOKE("minimize_to_tray")),
	/**
	 *  Engines for the plugin packaging picker: every machine-registered engine plus the
	 *  plugin's remembered (browsed) ones, validated; stale remembered entries are pruned
	 *  from `.uep/local.json` as a side effect. Sorted newest-first.
	 */
	listEngines: (pluginPath: string) => typedError<EngineEntry[], AppError>(__TAURI_INVOKE("list_engines", { pluginPath })),
	/**
	 *  Validate a browsed engine folder and remember it for this plugin; returns its
	 *  picker entry. Errors if the folder isn't a valid Unreal Engine root.
	 */
	addCustomEngine: (pluginPath: string, engineDir: string) => typedError<EngineEntry, AppError>(__TAURI_INVOKE("add_custom_engine", { pluginPath, engineDir })),
	/**
	 *  Resolve a package request into the read-only command preview + output dir (drives
	 *  the Actions tab's live command box + "folder exists" hint). `{date}`/`{time}`
	 *  resolve to now.
	 */
	previewPluginPackage: (req: PluginPackageRequest) => typedError<PluginPreview, AppError>(__TAURI_INVOKE("preview_plugin_package", { req })),
	/**
	 *  Resolve + launch a `BuildPlugin` run. Returns the run id; progress arrives via
	 *  `uep://run-*` (same as a build). Refuses a second concurrent run.
	 */
	startPluginPackage: (req: PluginPackageRequest) => typedError<string, AppError>(__TAURI_INVOKE("start_plugin_package", { req })),
	/**
	 *  Load the plugin's machine-local Actions settings (`<plugin_root>/.uap/settings.json`)
	 *  - remembered engines + last-used output folder + folder name.
	 */
	loadPluginSettings: (pluginPath: string) => typedError<PluginSettings, AppError>(__TAURI_INVOKE("load_plugin_settings", { pluginPath })),
	/**
	 *  Persist the plugin's package output folder + folder-name template into its
	 *  `.uap/settings.json` (read-modify-write, so the remembered engines are untouched).
	 */
	savePluginOutput: (pluginPath: string, outputDir: string, folderName: string) => typedError<null, AppError>(__TAURI_INVOKE("save_plugin_output", { pluginPath, outputDir, folderName })),
	/**
	 *  Launch a **Resave** run (`-run=ResavePackages`) on the open project - bakes in Core
	 *  Redirects, fixes up object redirectors, re-serializes assets. Returns the run id;
	 *  progress arrives via `uep://run-*`.
	 */
	startResave: (options: ResaveOptions) => typedError<string, AppError>(__TAURI_INVOKE("start_resave", { options })),
	/**
	 *  Launch a **Validate** run (`-run=DataValidation`) on the open project - runs the enabled
	 *  asset validators. Returns the run id; progress arrives via `uep://run-*`.
	 */
	startValidate: (options: ValidateOptions) => typedError<string, AppError>(__TAURI_INVOKE("start_validate", { options })),
	/**
	 *  Delete the open project's `.uep/` (or open plugin's `.uap/`), forget its recent, and
	 *  clear it from managed state. The gate opens a project XOR a plugin; project takes
	 *  precedence. Heavy delete → off the UI thread.
	 */
	removeUepData: () => typedError<RemovedUep, AppError>(__TAURI_INVOKE("remove_uep_data")),
};

/* Types */
/**  Serializable error for the IPC boundary (the UI switches on `kind`). */
export type AppError = { kind: "invalidProject"; message: string } | { kind: "invalidEngine"; message: string } | { kind: "engineNotFound"; message: string } | 
/**  Profile/template validation failed (one message per problem, newline-joined). */
{ kind: "validation"; message: string } | { kind: "io"; message: string };

export type AppSettings = {
	theme: Theme,
	/**  Show an OS toast when a build finishes (success/failed/cancelled). */
	notifyOnFinish: boolean,
	/**  Attach a sound to that toast (only meaningful when `notify_on_finish`). */
	notifySound: boolean,
};

/**
 *  Archive phase - copies the finished build to `output`. On by default. **Requires
 *  Stage** (it archives the staged tree), so it is forced off when Stage is off.
 */
export type ArchiveCfg = {
	enabled?: boolean,
	/**  Verbatim args merged into the shared Stage·Pak·Archive command. */
	additionalArgs?: string,
};

/**
 *  Build phase. On by default; off ⇒ reuse existing binaries (downstream phases
 *  keep `-skipbuild`). `clean` forces a from-scratch build; `-noP4` is a default-on
 *  toggle.
 */
export type BuildCfg = {
	/**  Whether the Build (compile) phase runs. */
	enabled?: boolean,
	/**  `-clean` - wipe intermediates first (mutually exclusive with incremental cook). */
	clean?: boolean,
	/**  `-noP4` - disable Perforce. Default on (the common solo-dev case). */
	noP4?: boolean,
	/**  Verbatim args appended to the UBT build command. */
	additionalArgs?: string,
};

/**
 *  Backs **both** a template and a profile (`docs/data-storage.md`). A template
 *  leaves `target` / `cook.maps` / `copy_extras.items` empty; a profile fills
 *  them. Self-contained: editing a template later never mutates existing profiles.
 */
export type BuildConfig = {
	schemaVersion: number,
	/**  Stable id (file stem on disk). */
	id: string,
	name: string,
	platform?: Platform,
	config?: Configuration,
	/**  Project-specific (`None` in templates). */
	target?: string | null,
	phases?: Phases,
	output?: Output,
	/**  Provenance only (which template a profile was created from); no live link. */
	basedOnTemplate?: string | null,
	/**
	 *  `true` only for the fixed built-in templates (Development, Shipping, …) -
	 *  cannot be deleted or edited; the clone bases. Never set on profiles or
	 *  user templates (the copy-on-create transforms reset it).
	 */
	builtin?: boolean,
};

/**
 *  One build's record. Self-contained and lean; the SQLite index ([`super::index`])
 *  is derived from these files, so they remain the source of truth.
 */
export type BuildRecord = {
	schemaVersion: number,
	/**  Stable id (the run id); also the `<buildId>/` folder name. */
	buildId: string,
	/**  Build start, epoch milliseconds. */
	startedAtMs: number | null,
	/**  Wall-clock total seconds (may be < Σ phase durations when parallel). */
	duration: number | null,
	/**  Final archived build size in bytes (0 if the build never archived). */
	buildSize: number | null,
	/**
	 *  Warning / error lines tallied from the streamed build output by the
	 *  [`super::super::runner::classify`] classifier. Counts **real child-process
	 *  output only** - executor-synthesized lines (command echo, "exited with code
	 *  N", cancel notices) are excluded. `#[serde(default)]` ⇒ pre-feature records
	 *  read 0 and still deserialize (so they never vanish from history).
	 */
	warningCount?: number,
	errorCount?: number,
	outputPath: string,
	/**  Output dir's modified time (epoch ms) - the "Open location" integrity basis. */
	outputMtimeMs: number | null,
	phases: PhaseTiming[],
	/**  Flat, reverse-mappable tags: platform, config, target, status. */
	tags: string[],
};

export type CleanOutcome = {
	removed: Removed[],
	reclaimedBytes: number | null,
};

/**
 *  A footprint reclaim category - the stable, serializable bucket a Clean-tab leaf and a
 *  Clean-up phase selection belong to (`docs/build-footprint.md`). Grouped on the Clean
 *  tab as **Save** (`Staged`/`Cooked`/`Shader`), **Binaries** (`BinariesGame` +
 *  `BinariesPlugin`), **Intermediate** (`IntermediateGame` = the build cache, `Intermediate
 *  Other` = the editor/tool/scratch rest of the main `Intermediate/`, and `IntermediatePlugin`),
 *  and a standalone **Cache** (`DerivedData`, the local `DerivedDataCache/`). `IntermediateGame`
 *  is editor-safe (build only); `IntermediateOther` is what forces a full editor recompile,
 *  so it stays out of the auto Clean-up phase.
 */
export type CleanupCategory = "staged" | "cooked" | "shader" | "binariesGame" | "binariesPlugin" | "intermediateGame" | "intermediateOther" | "intermediatePlugin" | "derivedData";

export type CleanupCfg = {
	enabled?: boolean,
	categories?: CleanupCategory[],
	/**
	 *  Keep artifacts when a build fails (the default), so a failure stays
	 *  debuggable.
	 */
	onlyOnSuccess?: boolean,
};

export type Configuration = "Debug" | "DebugGame" | "Development" | "Test" | "Shipping";

export type CookCfg = {
	/**
	 *  Whether the Cook phase runs. On by default; off ⇒ reuse an existing cook
	 *  (the downstream BuildCookRun keeps `-skipcook`).
	 */
	enabled?: boolean,
	maps?: CookMaps,
	/**  `-cookcultures=` (empty ⇒ project cultures). */
	cultures?: string[],
	incremental?: IncrementalCookMode,
	/**  `-SkipCookingEditorContent` (smaller cooked output). */
	skipEditorContent?: boolean,
	/**  `-AdditionalCookerOptions="…"` - verbatim cooker escape hatch. */
	additionalOptions?: string,
};

/**  `All` ⇒ `-allmaps`; `List` ⇒ `-map=A+B` (project-specific, empty in a template). */
export type CookMaps = "all" | { list: string[] };

export type CopyExtrasCfg = {
	enabled?: boolean,
	items?: CopyItem[],
};

export type CopyItem = {
	/**  Project-relative source (file or folder). */
	from: string,
	/**  Build-output-relative destination (default the build root). */
	to?: string,
};

/**
 *  How a new profile is created - always a copy, never blank: `template` clones a
 *  template, `clone` clones another profile. `sourceId` names that source.
 */
export type CreateFromKind = "template" | "clone";

export type CreateRequest = {
	name: string,
	from: CreateFromKind,
	/**  Template id (`template`) or source profile id (`clone`). */
	sourceId: string,
};

/**
 *  A new user template - created only by cloning an existing template (e.g. the
 *  fixed `Default`); never blank.
 */
export type CreateTemplateRequest = {
	name: string,
	/**  Source template id to clone (a fixed built-in, or any user template). */
	sourceId: string,
};

/**
 *  Everything detected when a **plugin** is opened (fresh, never persisted). Lean
 *  by design: a plugin packages standalone (no engine association, no targets/maps),
 *  so this carries only what the Actions tab needs - identity + the `.uplugin`'s
 *  `EngineVersion` hint to pre-select a matching engine.
 */
export type DetectedPlugin = {
	/**  File stem of the `.uplugin` (the canonical plugin name UAT uses). */
	name: string,
	friendlyName: string,
	versionName: string,
	upluginPath: string,
	/**
	 *  Directory containing the `.uplugin` (where `-package` output and the
	 *  `.uep/local.json` remembered-engines file are anchored).
	 */
	pluginRoot: string,
	/**  `.uplugin`'s `EngineVersion` (e.g. `"5.5"`), or `None` if unset. */
	engineVersion: string | null,
};

/**  Everything detected when a project is opened (fresh, never persisted). */
export type DetectedProject = {
	name: string,
	uprojectPath: string,
	projectRoot: string,
	engineAssociation: string,
	engine: EngineInfo,
	projectType: ProjectType,
	targets: TargetInfo[],
	maps: MapInventory,
	plugins: string[],
};

/**  One selectable engine in the plugin packaging picker. */
export type EngineEntry = {
	/**  Engine root path - the stable id/value (unique even when two builds share a version). */
	root: string,
	/**  Short version (e.g. `"5.5"`). */
	version: string,
	kind: EngineKind,
	/**  Display label (`"UE 5.5"` for launcher installs, `"<folder> (5.5)"` for source). */
	label: string,
	source: EngineSource,
};

export type EngineInfo = {
	root: string,
	version: EngineVersion,
	kind: EngineKind,
};

export type EngineKind = 
/**  Custom/source build (a GUID association, resolved via HKCU Builds / Install.ini). */
"source" | 
/**  Launcher / binary install (a version-string association). */
"launcher";

/**
 *  Where an engine entry came from - a machine registration vs a folder the user
 *  browsed for (remembered per-plugin). Display-only; both build identically.
 */
export type EngineSource = "registry" | "custom";

export type EngineVersion = {
	major: number,
	minor: number,
	patch: number,
};

export type FilterOptions = {
	platform: string[],
	config: string[],
	target: string[],
	status: string[],
};

export type FootprintLocation = {
	path: string,
	rel: string,
	sizeBytes: number | null,
};

/**
 *  A node in the Clean-tab tree. A **leaf** is selectable and carries a `category` +
 *  `locations`; a **grouping** node (`Save`, `Binaries`, `Intermediate` → `Game`/`Plugin`)
 *  has an empty `id`, `selectable = false`, and aggregates its `children`.
 */
export type FootprintNode = {
	/**  Stable id the cleaner resolves back to targets (empty for grouping nodes). */
	id: string,
	label: string,
	category: CleanupCategory | null,
	selectable: boolean,
	sizeBytes: number | null,
	locations: FootprintLocation[],
	children: FootprintNode[],
};

export type FootprintReport = {
	/**  Top-level groups: Save, Binaries, Intermediate, Cache. */
	groups: FootprintNode[],
	totalBytes: number | null,
};

export type HistoryDetail = {
	record: BuildRecord,
	/**
	 *  The saved log, re-classified for severity tinting on replay; each line's
	 *  phase index is restored from the `build.idx` sidecar (0 for older records).
	 */
	lines: LogLine[],
};

export type HistoryFilter = {
	platform: string | null,
	config: string | null,
	target: string | null,
	status: string | null,
};

export type HistoryPage = {
	/**  The requested page of records (newest first). */
	records: BuildRecord[],
	/**  Records matching the filter - the page count divides this. */
	filteredTotal: number | null,
	/**  Records regardless of filter - the "x of y builds" line. */
	grandTotal: number | null,
	/**  Distinct tag values present, split by dimension (drives the filter menus). */
	options: FilterOptions,
};

/**
 *  Incremental cook strategy. `None` ⇒ full cook (default, the only release-safe
 *  choice). `ModifiedOnly` ⇒ legacy `-iterativecooking` (dev-only staleness
 *  footgun - `docs/build-commands.md` §7). `ModifiedAndDependencies` ⇒
 *  `-cookincremental` (UE 5.6+). Mutually exclusive with a Build clean.
 */
export type IncrementalCookMode = "none" | "modifiedOnly" | "modifiedAndDependencies";

export type LocationCheck = {
	path: string,
	exists: boolean,
	/**
	 *  The folder may no longer hold *this* build - a later build reused the same
	 *  folder, or its mtime drifted from the record's.
	 */
	changed: boolean,
};

export type LogLine = {
	seq: number,
	phaseIndex: number,
	severity: Severity,
	text: string,
};

export type MapInventory = {
	/**  `/Game/...` package paths for every `.umap` under `Content/`, sorted. */
	maps: string[],
	gameDefault: string | null,
	editorStartup: string | null,
};

export type Output = {
	/**  REQUIRED on a profile (Archive is mandatory). May be empty in a template. */
	baseDir: string,
	folderTemplate?: string,
};

export type OutputCheck = {
	path: string,
	exists: boolean,
};

export type PakCfg = {
	/**  `-pak` (off ⇒ loose files). */
	enabled?: boolean,
	/**  `-iostore` (`.utoc`/`.ucas`; pulls Pak on). */
	ioStore?: boolean,
	/**  `-compressed` (Oodle/Kraken payload). */
	compressed?: boolean,
	/**  `-package` (platform-native distributable). */
	package?: boolean,
	/**  Verbatim args merged into the shared Stage·Pak·Archive command. */
	additionalArgs?: string,
};

/**
 *  One resolved execution unit. `phase` is its primary registry phase (the
 *  Stage·Pak·Archive unit reports `Stage`); `External` units carry a `program` +
 *  `args` to spawn, `App` units carry only the `preview` text.
 */
export type PhaseCommand = {
	phase: PhaseId,
	label: string,
	kind: PhaseKind,
	/**  External only - the executable/batch file to run. */
	program: string | null,
	/**  External only - the argument vector (excludes `program`). */
	args: string[],
	/**  The read-only display string: the full command line, or the app action. */
	preview: string,
};

/**
 *  Stable phase keys - the editor's per-phase keys. **camelCase on the wire**, so
 *  the serialized id (`"copyExtras"`) matches the `Phases` cfg field names and the
 *  TS phase keys (one source of truth; the frontend indexes phase config by this id
 *  with no mapping). The human-facing name lives in `PhaseInfo::label`, not here.
 */
export type PhaseId = "build" | "cook" | "stage" | "pak" | "archive" | "copyExtras" | "cleanup";

/**  Serializable view of a registry entry (for the editor over IPC). */
export type PhaseInfo = {
	id: PhaseId,
	label: string,
	order: number,
	dependsOn: PhaseId[],
	/**
	 *  Gating phases (see `PhaseDef::gated_by`) - the editor derives a phase's
	 *  locked state from this, so adding a gated phase needs no frontend change.
	 */
	gatedBy: PhaseId[],
	requiredness: Requiredness,
	kind: PhaseKind,
};

/**
 *  `External` spawns a child process (UBT / RunUAT); `App` is an in-process task
 *  (fs copy, footprint cleanup) with no external command.
 */
export type PhaseKind = "external" | "app";

/**
 *  One graph node = one execution unit (the Stage·Pak·Archive unit is a single
 *  node, matching the design). `level` is its scheduling stage = its graph column
 *  (parallel siblings share a column).
 */
export type PhaseNode = {
	index: number,
	label: string,
	phase: PhaseId,
	kind: PhaseKind,
	level: number,
	/**
	 *  The resolved command line (`External`) or app-action preview (`App`) - shown
	 *  read-only in the Build Logs "Command" island.
	 */
	command: string,
	status: PhaseStatus,
	startOffsetMs: number | null,
	durationMs: number | null,
};

export type PhaseStatus = "pending" | "running" | "success" | "failed" | "skipped" | "cancelled";

/**
 *  Per-phase timing - start offset + duration reconstruct overlap (a Gantt) and
 *  trends without a redundant end stamp. One entry per executed pipeline phase.
 */
export type PhaseTiming = {
	/**  The execution unit's label (e.g. "Build", "Cook", "Stage · Pak · Archive"). */
	phase: string,
	/**  Seconds from build start. */
	startOffset: number | null,
	/**  Seconds the phase ran. */
	duration: number | null,
	/**  `Success` | `Failed` | `Skipped` | `Cancelled`. */
	status: string,
	/**
	 *  `external` (child process) | `app` (in-process task). `#[serde(default)]` ⇒
	 *  older records deserialize with `""`, and the UI infers it from the label.
	 */
	kind?: string,
	/**
	 *  Resolved command line for an external phase (empty for app phases) - lets the
	 *  Build Logs "Command" island show it on replay.
	 */
	command?: string,
};

/**
 *  Per-phase config in pipeline order. Each phase owns its `enabled` toggle plus
 *  its parameters; Build/Cook/Stage/Pak/Archive each carry a verbatim
 *  `additional_args` escape hatch. Archive's output destination lives in `Output`
 *  (the editor's Archive island shows both).
 */
export type Phases = {
	build?: BuildCfg,
	cook?: CookCfg,
	stage?: StageCfg,
	pak?: PakCfg,
	archive?: ArchiveCfg,
	copyExtras?: CopyExtrasCfg,
	cleanup?: CleanupCfg,
};

export type Platform = "Win64" | "Linux" | "Mac";

export type PluginPackageRequest = {
	pluginPath: string,
	engineRoot: string,
	/**  User-picked output folder (the package dir's parent). */
	baseDir: string,
	/**  Folder-name template (tokens `{plugin}` `{version}` `{engine}` `{date}` `{time}`). */
	folderTemplate: string,
	/**  Remove `<package>/Binaries` + `<package>/Intermediate` on success (FAB). */
	stripBinariesIntermediate: boolean,
};

export type PluginPreview = {
	/**  Resolved `RunUAT BuildPlugin …` command line. */
	command: string,
	/**  Resolved `-package` directory (`base_dir / rendered folder`). */
	packageDir: string,
	/**  Whether that directory already exists (it'll be cleared before packaging). */
	exists: boolean,
};

/**  The plugin's machine-local Actions settings (one JSON file). */
export type PluginSettings = {
	/**  Engine roots the user browsed for (remembered; stale ones pruned when listed). */
	engines?: string[],
	/**  Last-used package output base dir. */
	outputDir?: string,
	/**  Last-used package folder-name template. */
	folderName?: string,
};

export type ProjectType = 
/**  Has a `Source/` tree with `*.Target.cs` / `*.Build.cs`. */
"cpp" | "blueprint";

export type ProjectValidation = {
	name: string,
	engineAssociation: string,
	/**  `None` ⇒ the engine could not be resolved; the UI must prompt Locate. */
	engine: EngineInfo | null,
};

export type RecentEntry = {
	name: string,
	/**  Descriptor path - a `.uproject` or `.uplugin` (see `kind`). */
	path: string,
	/**  Project vs plugin - drives the gate's PROJECT/PLUGIN tag + which open flow runs. */
	kind: RecentKind,
	/**
	 *  Pinned to the top of the recents list (persisted). The user toggles it via
	 *  the star in the gate; sorts above unpinned entries regardless of recency.
	 */
	starred: boolean,
	lastOpenedMs: number | null,
	/**  The descriptor (`.uproject`/`.uplugin`) exists and parses. */
	valid: boolean,
	/**  An engine was resolved + validated for this project's association. */
	engineValid: boolean,
	engineVersion: string | null,
	engineKind: EngineKind | null,
	/**
	 *  Resolved engine root, or the stale saved path when invalid (shown so the
	 *  user can see what to fix). `None` when nothing is known.
	 */
	enginePath: string | null,
	engineAssociation: string | null,
	/**
	 *  The `.uplugin`'s `VersionName` (e.g. `"1.2.0"`), shown in the gate; `None`
	 *  for projects.
	 */
	version: string | null,
};

/**
 *  What a recents entry points at - a project `.uproject` or a plugin `.uplugin`.
 *  The gate shows this as a PROJECT / PLUGIN tag and routes the open accordingly.
 *  `#[serde(default)]` ⇒ pre-feature recents (which had no `kind`) load as projects.
 */
export type RecentKind = "project" | "plugin";

export type Removed = {
	rel: string,
	path: string,
	sizeBytes: number | null,
	deleted: boolean,
};

export type RemovedUep = {
	/**  The deleted data folder (`<project>/.uep` or `<plugin>/.uap`). */
	path: string,
	/**  Whether the folder existed (false ⇒ nothing to delete, but the recent is still cleared). */
	existed: boolean,
	freedBytes: number | null,
};

/**
 *  Editor metadata. Every MVP phase is now toggleable, so the registry marks them
 *  all `Optional`; the Stage-gate for Pak/Archive lives in `gated_by`, not here. The
 *  other variants are kept for forthcoming phases.
 */
export type Requiredness = 
/**  Always runs, toggle locked on. (Unused in the MVP - all phases toggle.) */
"always" | 
/**  Required only for C++ projects. */
"forCpp" | 
/**  Pulled on by another enabled phase. */
"ifDependedOn" | 
/**  Free - the user chooses (every MVP phase). */
"optional";

/**  Options for the Resave tool (resaves the whole project). */
export type ResaveOptions = {
	/**  `-ProjectOnly` - skip the engine's own content (on by default in the UI). */
	projectOnly: boolean,
	fixupRedirectors: boolean,
	skipShaderCompile: boolean,
};

/**
 *  The full live state of a run - returned by `active_run` so a freshly-opened
 *  Build Logs window can render the graph + backfill the console before following
 *  live events.
 */
export type RunSnapshot = {
	runId: string,
	project: string,
	platform: string,
	config: string,
	target: string,
	outputDir: string,
	startedMs: number | null,
	status: RunStatus,
	phases: PhaseNode[],
	lines: LogLine[],
	/**
	 *  Single resolved command line - set for a plugin-package run or an editor-commandlet
	 *  tool run (the Run Log window shows it). Empty for a build run, whose per-phase
	 *  commands live on the `phases` nodes instead.
	 */
	command: string,
	/**
	 *  Heading for the single-command Run Log window: "Package Plugin" for a plugin
	 *  package, the tool name ("Resave Assets" / "Validate Assets") for a commandlet tool.
	 *  Empty for a build run (the Build Logs window has its own heading).
	 */
	title: string,
};

export type RunStatus = "running" | "success" | "failed" | "cancelled";

/**
 *  Per-line severity. `lowercase` on the wire to match the other camelCase/lower
 *  enums the editor consumes.
 */
export type Severity = "info" | "warning" | "error";

export type StageCfg = {
	/**
	 *  Whether the Stage phase runs. **Gate for Pak + Archive** - both run inside
	 *  the staged tree, so turning Stage off forces both off.
	 */
	enabled?: boolean,
	/**  `-prereqs` (stage the VC++ redist installer). */
	prereqs?: boolean,
	/**  `-distribution` (store-ready flag; mainly console/mobile). */
	forDistribution?: boolean,
	/**  `false` ⇒ emit `-nodebuginfo` (drop `.pdb`, a footprint lever). */
	debugSymbols?: boolean,
	/**  `-separatedebuginfo` (stage symbols into a separate dir). */
	separateDebugInfo?: boolean,
	/**  Verbatim args merged into the shared Stage·Pak·Archive command. */
	additionalArgs?: string,
};

export type TargetInfo = {
	name: string,
	targetType: TargetType,
};

export type TargetType = "Game" | "Editor" | "Client" | "Server" | "Program" | "Unknown";

/**
 *  Two explicit color schemes (no system/auto for MVP). Lowercased over the IPC
 *  boundary so it maps straight onto Mantine's `'light' | 'dark'`.
 */
export type Theme = "light" | "dark";

/**
 *  Options for the Validate tool. `skip_engine_content` ⇒ the default project-only scope;
 *  unticking it passes `-includeengine`. `asset_type` (empty ⇒ all) restricts validation to
 *  one class and its subclasses (a short name or a full `/Script/...` path).
 */
export type ValidateOptions = {
	skipEngineContent: boolean,
	assetType: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

